name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build a docker image and run tests
      run: |
        docker build --target builder -t "${GITHUB_REPOSITORY}:${GITHUB_SHA}" .
        docker run "${GITHUB_REPOSITORY}:${GITHUB_SHA}" dotnet test
